/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as ShadesRouteImport } from './routes/shades'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as AdminRouteImport } from './routes/_admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedScanRouteImport } from './routes/_authenticated.scan'
import { Route as AuthenticatedRiskAnalysisRouteImport } from './routes/_authenticated.risk-analysis'
import { Route as AuthenticatedRecommendationsRouteImport } from './routes/_authenticated.recommendations'
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated.profile'
import { Route as AuthenticatedHabitTrackerRouteImport } from './routes/_authenticated.habit-tracker'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated.dashboard'
import { Route as AdminIndexRouteImport } from './routes/_admin.index'
import { Route as AdminUsersRouteImport } from './routes/_admin.users'
import { Route as AdminScansRouteImport } from './routes/_admin.scans'
import { Route as AdminRecommendationsRouteImport } from './routes/_admin.recommendations'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ShadesRoute = ShadesRouteImport.update({
  id: '/shades',
  path: '/shades',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/_admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedScanRoute = AuthenticatedScanRouteImport.update({
  id: '/scan',
  path: '/scan',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedRiskAnalysisRoute =
  AuthenticatedRiskAnalysisRouteImport.update({
    id: '/risk-analysis',
    path: '/risk-analysis',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedRecommendationsRoute =
  AuthenticatedRecommendationsRouteImport.update({
    id: '/recommendations',
    path: '/recommendations',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedHabitTrackerRoute =
  AuthenticatedHabitTrackerRouteImport.update({
    id: '/habit-tracker',
    path: '/habit-tracker',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/admin',
  getParentRoute: () => AdminRoute,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/admin/users',
  getParentRoute: () => AdminRoute,
} as any)
const AdminScansRoute = AdminScansRouteImport.update({
  id: '/scans',
  path: '/admin/scans',
  getParentRoute: () => AdminRoute,
} as any)
const AdminRecommendationsRoute = AdminRecommendationsRouteImport.update({
  id: '/recommendations',
  path: '/admin/recommendations',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/shades': typeof ShadesRoute
  '/signup': typeof SignupRoute
  '/admin': typeof AdminIndexRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/scans': typeof AdminScansRoute
  '/admin/recommendations': typeof AdminRecommendationsRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/habit-tracker': typeof AuthenticatedHabitTrackerRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/recommendations': typeof AuthenticatedRecommendationsRoute
  '/risk-analysis': typeof AuthenticatedRiskAnalysisRoute
  '/scan': typeof AuthenticatedScanRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/shades': typeof ShadesRoute
  '/signup': typeof SignupRoute
  '/admin': typeof AdminIndexRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/scans': typeof AdminScansRoute
  '/admin/recommendations': typeof AdminRecommendationsRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/habit-tracker': typeof AuthenticatedHabitTrackerRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/recommendations': typeof AuthenticatedRecommendationsRoute
  '/risk-analysis': typeof AuthenticatedRiskAnalysisRoute
  '/scan': typeof AuthenticatedScanRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_admin': typeof AdminRouteWithChildren
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/shades': typeof ShadesRoute
  '/signup': typeof SignupRoute
  '/_admin/': typeof AdminIndexRoute
  '/_admin/users': typeof AdminUsersRoute
  '/_admin/scans': typeof AdminScansRoute
  '/_admin/recommendations': typeof AdminRecommendationsRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/habit-tracker': typeof AuthenticatedHabitTrackerRoute
  '/_authenticated/profile': typeof AuthenticatedProfileRoute
  '/_authenticated/recommendations': typeof AuthenticatedRecommendationsRoute
  '/_authenticated/risk-analysis': typeof AuthenticatedRiskAnalysisRoute
  '/_authenticated/scan': typeof AuthenticatedScanRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/shades'
    | '/signup'
    | '/admin'
    | '/admin/users'
    | '/admin/scans'
    | '/admin/recommendations'
    | '/dashboard'
    | '/habit-tracker'
    | '/profile'
    | '/recommendations'
    | '/risk-analysis'
    | '/scan'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/shades'
    | '/signup'
    | '/admin'
    | '/admin/users'
    | '/admin/scans'
    | '/admin/recommendations'
    | '/dashboard'
    | '/habit-tracker'
    | '/profile'
    | '/recommendations'
    | '/risk-analysis'
    | '/scan'
  id:
    | '__root__'
    | '/'
    | '/_admin'
    | '/_authenticated'
    | '/login'
    | '/shades'
    | '/signup'
    | '/_admin/'
    | '/_admin/users'
    | '/_admin/scans'
    | '/_admin/recommendations'
    | '/_authenticated/dashboard'
    | '/_authenticated/habit-tracker'
    | '/_authenticated/profile'
    | '/_authenticated/recommendations'
    | '/_authenticated/risk-analysis'
    | '/_authenticated/scan'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
  ShadesRoute: typeof ShadesRoute
  SignupRoute: typeof SignupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shades': {
      id: '/shades'
      path: '/shades'
      fullPath: '/shades'
      preLoaderRoute: typeof ShadesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_admin': {
      id: '/_admin'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/scan': {
      id: '/_authenticated/scan'
      path: '/scan'
      fullPath: '/scan'
      preLoaderRoute: typeof AuthenticatedScanRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/risk-analysis': {
      id: '/_authenticated/risk-analysis'
      path: '/risk-analysis'
      fullPath: '/risk-analysis'
      preLoaderRoute: typeof AuthenticatedRiskAnalysisRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/recommendations': {
      id: '/_authenticated/recommendations'
      path: '/recommendations'
      fullPath: '/recommendations'
      preLoaderRoute: typeof AuthenticatedRecommendationsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/habit-tracker': {
      id: '/_authenticated/habit-tracker'
      path: '/habit-tracker'
      fullPath: '/habit-tracker'
      preLoaderRoute: typeof AuthenticatedHabitTrackerRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_admin/': {
      id: '/_admin/'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/users': {
      id: '/_admin/users'
      path: '/admin/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/scans': {
      id: '/_admin/scans'
      path: '/admin/scans'
      fullPath: '/admin/scans'
      preLoaderRoute: typeof AdminScansRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/recommendations': {
      id: '/_admin/recommendations'
      path: '/admin/recommendations'
      fullPath: '/admin/recommendations'
      preLoaderRoute: typeof AdminRecommendationsRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedHabitTrackerRoute: typeof AuthenticatedHabitTrackerRoute
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRoute
  AuthenticatedRecommendationsRoute: typeof AuthenticatedRecommendationsRoute
  AuthenticatedRiskAnalysisRoute: typeof AuthenticatedRiskAnalysisRoute
  AuthenticatedScanRoute: typeof AuthenticatedScanRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedHabitTrackerRoute: AuthenticatedHabitTrackerRoute,
  AuthenticatedProfileRoute: AuthenticatedProfileRoute,
  AuthenticatedRecommendationsRoute: AuthenticatedRecommendationsRoute,
  AuthenticatedRiskAnalysisRoute: AuthenticatedRiskAnalysisRoute,
  AuthenticatedScanRoute: AuthenticatedScanRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

interface AdminRouteChildren {
  AdminIndexRoute: typeof AdminIndexRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AdminScansRoute: typeof AdminScansRoute
  AdminRecommendationsRoute: typeof AdminRecommendationsRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminIndexRoute: AdminIndexRoute,
  AdminUsersRoute: AdminUsersRoute,
  AdminScansRoute: AdminScansRoute,
  AdminRecommendationsRoute: AdminRecommendationsRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
  ShadesRoute: ShadesRoute,
  SignupRoute: SignupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
