/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminUsersRouteImport } from './routes/admin.users'
import { Route as AdminShadesRouteImport } from './routes/admin.shades'
import { Route as AdminSettingsRouteImport } from './routes/admin.settings'
import { Route as AdminScansRouteImport } from './routes/admin.scans'
import { Route as AdminRecommendationsRouteImport } from './routes/admin.recommendations'
import { Route as AdminArticlesRouteImport } from './routes/admin.articles'
import { Route as AdminApiDocsRouteImport } from './routes/admin.api-docs'
import { Route as AuthenticatedShadesRouteImport } from './routes/_authenticated.shades'
import { Route as AuthenticatedScanRouteImport } from './routes/_authenticated.scan'
import { Route as AuthenticatedRiskAnalysisRouteImport } from './routes/_authenticated.risk-analysis'
import { Route as AuthenticatedRecommendationsRouteImport } from './routes/_authenticated.recommendations'
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated.profile'
import { Route as AuthenticatedHabitTrackerRouteImport } from './routes/_authenticated.habit-tracker'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated.dashboard'
import { Route as ApiMobileScansRouteImport } from './routes/api/mobile/scans'
import { Route as ApiMobileRiskAnalysisRouteImport } from './routes/api/mobile/risk-analysis'
import { Route as ApiMobileRecommendationsRouteImport } from './routes/api/mobile/recommendations'
import { Route as ApiMobileProfileRouteImport } from './routes/api/mobile/profile'
import { Route as ApiMobileHabitsRouteImport } from './routes/api/mobile/habits'
import { Route as ApiMobileHabitInsightsRouteImport } from './routes/api/mobile/habit-insights'
import { Route as ApiMobileArticlesRouteImport } from './routes/api/mobile/articles'
import { Route as ApiMobileAnalyzeRouteImport } from './routes/api/mobile/analyze'
import { Route as ApiMobileRecommendationsGenerateRouteImport } from './routes/api/mobile/recommendations.generate'
import { Route as ApiMobileAuthSignupRouteImport } from './routes/api/mobile/auth.signup'
import { Route as ApiMobileAuthLoginRouteImport } from './routes/api/mobile/auth.login'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRoute,
} as any)
const AdminShadesRoute = AdminShadesRouteImport.update({
  id: '/shades',
  path: '/shades',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminScansRoute = AdminScansRouteImport.update({
  id: '/scans',
  path: '/scans',
  getParentRoute: () => AdminRoute,
} as any)
const AdminRecommendationsRoute = AdminRecommendationsRouteImport.update({
  id: '/recommendations',
  path: '/recommendations',
  getParentRoute: () => AdminRoute,
} as any)
const AdminArticlesRoute = AdminArticlesRouteImport.update({
  id: '/articles',
  path: '/articles',
  getParentRoute: () => AdminRoute,
} as any)
const AdminApiDocsRoute = AdminApiDocsRouteImport.update({
  id: '/api-docs',
  path: '/api-docs',
  getParentRoute: () => AdminRoute,
} as any)
const AuthenticatedShadesRoute = AuthenticatedShadesRouteImport.update({
  id: '/shades',
  path: '/shades',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedScanRoute = AuthenticatedScanRouteImport.update({
  id: '/scan',
  path: '/scan',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedRiskAnalysisRoute =
  AuthenticatedRiskAnalysisRouteImport.update({
    id: '/risk-analysis',
    path: '/risk-analysis',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedRecommendationsRoute =
  AuthenticatedRecommendationsRouteImport.update({
    id: '/recommendations',
    path: '/recommendations',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedHabitTrackerRoute =
  AuthenticatedHabitTrackerRouteImport.update({
    id: '/habit-tracker',
    path: '/habit-tracker',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const ApiMobileScansRoute = ApiMobileScansRouteImport.update({
  id: '/api/mobile/scans',
  path: '/api/mobile/scans',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMobileRiskAnalysisRoute = ApiMobileRiskAnalysisRouteImport.update({
  id: '/api/mobile/risk-analysis',
  path: '/api/mobile/risk-analysis',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMobileRecommendationsRoute =
  ApiMobileRecommendationsRouteImport.update({
    id: '/api/mobile/recommendations',
    path: '/api/mobile/recommendations',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiMobileProfileRoute = ApiMobileProfileRouteImport.update({
  id: '/api/mobile/profile',
  path: '/api/mobile/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMobileHabitsRoute = ApiMobileHabitsRouteImport.update({
  id: '/api/mobile/habits',
  path: '/api/mobile/habits',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMobileHabitInsightsRoute = ApiMobileHabitInsightsRouteImport.update({
  id: '/api/mobile/habit-insights',
  path: '/api/mobile/habit-insights',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMobileArticlesRoute = ApiMobileArticlesRouteImport.update({
  id: '/api/mobile/articles',
  path: '/api/mobile/articles',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMobileAnalyzeRoute = ApiMobileAnalyzeRouteImport.update({
  id: '/api/mobile/analyze',
  path: '/api/mobile/analyze',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMobileRecommendationsGenerateRoute =
  ApiMobileRecommendationsGenerateRouteImport.update({
    id: '/generate',
    path: '/generate',
    getParentRoute: () => ApiMobileRecommendationsRoute,
  } as any)
const ApiMobileAuthSignupRoute = ApiMobileAuthSignupRouteImport.update({
  id: '/api/mobile/auth/signup',
  path: '/api/mobile/auth/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMobileAuthLoginRoute = ApiMobileAuthLoginRouteImport.update({
  id: '/api/mobile/auth/login',
  path: '/api/mobile/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/habit-tracker': typeof AuthenticatedHabitTrackerRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/recommendations': typeof AuthenticatedRecommendationsRoute
  '/risk-analysis': typeof AuthenticatedRiskAnalysisRoute
  '/scan': typeof AuthenticatedScanRoute
  '/shades': typeof AuthenticatedShadesRoute
  '/admin/api-docs': typeof AdminApiDocsRoute
  '/admin/articles': typeof AdminArticlesRoute
  '/admin/recommendations': typeof AdminRecommendationsRoute
  '/admin/scans': typeof AdminScansRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/shades': typeof AdminShadesRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/': typeof AdminIndexRoute
  '/api/mobile/analyze': typeof ApiMobileAnalyzeRoute
  '/api/mobile/articles': typeof ApiMobileArticlesRoute
  '/api/mobile/habit-insights': typeof ApiMobileHabitInsightsRoute
  '/api/mobile/habits': typeof ApiMobileHabitsRoute
  '/api/mobile/profile': typeof ApiMobileProfileRoute
  '/api/mobile/recommendations': typeof ApiMobileRecommendationsRouteWithChildren
  '/api/mobile/risk-analysis': typeof ApiMobileRiskAnalysisRoute
  '/api/mobile/scans': typeof ApiMobileScansRoute
  '/api/mobile/auth/login': typeof ApiMobileAuthLoginRoute
  '/api/mobile/auth/signup': typeof ApiMobileAuthSignupRoute
  '/api/mobile/recommendations/generate': typeof ApiMobileRecommendationsGenerateRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/habit-tracker': typeof AuthenticatedHabitTrackerRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/recommendations': typeof AuthenticatedRecommendationsRoute
  '/risk-analysis': typeof AuthenticatedRiskAnalysisRoute
  '/scan': typeof AuthenticatedScanRoute
  '/shades': typeof AuthenticatedShadesRoute
  '/admin/api-docs': typeof AdminApiDocsRoute
  '/admin/articles': typeof AdminArticlesRoute
  '/admin/recommendations': typeof AdminRecommendationsRoute
  '/admin/scans': typeof AdminScansRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/shades': typeof AdminShadesRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin': typeof AdminIndexRoute
  '/api/mobile/analyze': typeof ApiMobileAnalyzeRoute
  '/api/mobile/articles': typeof ApiMobileArticlesRoute
  '/api/mobile/habit-insights': typeof ApiMobileHabitInsightsRoute
  '/api/mobile/habits': typeof ApiMobileHabitsRoute
  '/api/mobile/profile': typeof ApiMobileProfileRoute
  '/api/mobile/recommendations': typeof ApiMobileRecommendationsRouteWithChildren
  '/api/mobile/risk-analysis': typeof ApiMobileRiskAnalysisRoute
  '/api/mobile/scans': typeof ApiMobileScansRoute
  '/api/mobile/auth/login': typeof ApiMobileAuthLoginRoute
  '/api/mobile/auth/signup': typeof ApiMobileAuthSignupRoute
  '/api/mobile/recommendations/generate': typeof ApiMobileRecommendationsGenerateRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/admin': typeof AdminRouteWithChildren
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/habit-tracker': typeof AuthenticatedHabitTrackerRoute
  '/_authenticated/profile': typeof AuthenticatedProfileRoute
  '/_authenticated/recommendations': typeof AuthenticatedRecommendationsRoute
  '/_authenticated/risk-analysis': typeof AuthenticatedRiskAnalysisRoute
  '/_authenticated/scan': typeof AuthenticatedScanRoute
  '/_authenticated/shades': typeof AuthenticatedShadesRoute
  '/admin/api-docs': typeof AdminApiDocsRoute
  '/admin/articles': typeof AdminArticlesRoute
  '/admin/recommendations': typeof AdminRecommendationsRoute
  '/admin/scans': typeof AdminScansRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/shades': typeof AdminShadesRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/': typeof AdminIndexRoute
  '/api/mobile/analyze': typeof ApiMobileAnalyzeRoute
  '/api/mobile/articles': typeof ApiMobileArticlesRoute
  '/api/mobile/habit-insights': typeof ApiMobileHabitInsightsRoute
  '/api/mobile/habits': typeof ApiMobileHabitsRoute
  '/api/mobile/profile': typeof ApiMobileProfileRoute
  '/api/mobile/recommendations': typeof ApiMobileRecommendationsRouteWithChildren
  '/api/mobile/risk-analysis': typeof ApiMobileRiskAnalysisRoute
  '/api/mobile/scans': typeof ApiMobileScansRoute
  '/api/mobile/auth/login': typeof ApiMobileAuthLoginRoute
  '/api/mobile/auth/signup': typeof ApiMobileAuthSignupRoute
  '/api/mobile/recommendations/generate': typeof ApiMobileRecommendationsGenerateRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/login'
    | '/signup'
    | '/dashboard'
    | '/habit-tracker'
    | '/profile'
    | '/recommendations'
    | '/risk-analysis'
    | '/scan'
    | '/shades'
    | '/admin/api-docs'
    | '/admin/articles'
    | '/admin/recommendations'
    | '/admin/scans'
    | '/admin/settings'
    | '/admin/shades'
    | '/admin/users'
    | '/admin/'
    | '/api/mobile/analyze'
    | '/api/mobile/articles'
    | '/api/mobile/habit-insights'
    | '/api/mobile/habits'
    | '/api/mobile/profile'
    | '/api/mobile/recommendations'
    | '/api/mobile/risk-analysis'
    | '/api/mobile/scans'
    | '/api/mobile/auth/login'
    | '/api/mobile/auth/signup'
    | '/api/mobile/recommendations/generate'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/signup'
    | '/dashboard'
    | '/habit-tracker'
    | '/profile'
    | '/recommendations'
    | '/risk-analysis'
    | '/scan'
    | '/shades'
    | '/admin/api-docs'
    | '/admin/articles'
    | '/admin/recommendations'
    | '/admin/scans'
    | '/admin/settings'
    | '/admin/shades'
    | '/admin/users'
    | '/admin'
    | '/api/mobile/analyze'
    | '/api/mobile/articles'
    | '/api/mobile/habit-insights'
    | '/api/mobile/habits'
    | '/api/mobile/profile'
    | '/api/mobile/recommendations'
    | '/api/mobile/risk-analysis'
    | '/api/mobile/scans'
    | '/api/mobile/auth/login'
    | '/api/mobile/auth/signup'
    | '/api/mobile/recommendations/generate'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/admin'
    | '/login'
    | '/signup'
    | '/_authenticated/dashboard'
    | '/_authenticated/habit-tracker'
    | '/_authenticated/profile'
    | '/_authenticated/recommendations'
    | '/_authenticated/risk-analysis'
    | '/_authenticated/scan'
    | '/_authenticated/shades'
    | '/admin/api-docs'
    | '/admin/articles'
    | '/admin/recommendations'
    | '/admin/scans'
    | '/admin/settings'
    | '/admin/shades'
    | '/admin/users'
    | '/admin/'
    | '/api/mobile/analyze'
    | '/api/mobile/articles'
    | '/api/mobile/habit-insights'
    | '/api/mobile/habits'
    | '/api/mobile/profile'
    | '/api/mobile/recommendations'
    | '/api/mobile/risk-analysis'
    | '/api/mobile/scans'
    | '/api/mobile/auth/login'
    | '/api/mobile/auth/signup'
    | '/api/mobile/recommendations/generate'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  AdminRoute: typeof AdminRouteWithChildren
  LoginRoute: typeof LoginRoute
  SignupRoute: typeof SignupRoute
  ApiMobileAnalyzeRoute: typeof ApiMobileAnalyzeRoute
  ApiMobileArticlesRoute: typeof ApiMobileArticlesRoute
  ApiMobileHabitInsightsRoute: typeof ApiMobileHabitInsightsRoute
  ApiMobileHabitsRoute: typeof ApiMobileHabitsRoute
  ApiMobileProfileRoute: typeof ApiMobileProfileRoute
  ApiMobileRecommendationsRoute: typeof ApiMobileRecommendationsRouteWithChildren
  ApiMobileRiskAnalysisRoute: typeof ApiMobileRiskAnalysisRoute
  ApiMobileScansRoute: typeof ApiMobileScansRoute
  ApiMobileAuthLoginRoute: typeof ApiMobileAuthLoginRoute
  ApiMobileAuthSignupRoute: typeof ApiMobileAuthSignupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/shades': {
      id: '/admin/shades'
      path: '/shades'
      fullPath: '/admin/shades'
      preLoaderRoute: typeof AdminShadesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/scans': {
      id: '/admin/scans'
      path: '/scans'
      fullPath: '/admin/scans'
      preLoaderRoute: typeof AdminScansRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/recommendations': {
      id: '/admin/recommendations'
      path: '/recommendations'
      fullPath: '/admin/recommendations'
      preLoaderRoute: typeof AdminRecommendationsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/articles': {
      id: '/admin/articles'
      path: '/articles'
      fullPath: '/admin/articles'
      preLoaderRoute: typeof AdminArticlesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/api-docs': {
      id: '/admin/api-docs'
      path: '/api-docs'
      fullPath: '/admin/api-docs'
      preLoaderRoute: typeof AdminApiDocsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_authenticated/shades': {
      id: '/_authenticated/shades'
      path: '/shades'
      fullPath: '/shades'
      preLoaderRoute: typeof AuthenticatedShadesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/scan': {
      id: '/_authenticated/scan'
      path: '/scan'
      fullPath: '/scan'
      preLoaderRoute: typeof AuthenticatedScanRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/risk-analysis': {
      id: '/_authenticated/risk-analysis'
      path: '/risk-analysis'
      fullPath: '/risk-analysis'
      preLoaderRoute: typeof AuthenticatedRiskAnalysisRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/recommendations': {
      id: '/_authenticated/recommendations'
      path: '/recommendations'
      fullPath: '/recommendations'
      preLoaderRoute: typeof AuthenticatedRecommendationsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/habit-tracker': {
      id: '/_authenticated/habit-tracker'
      path: '/habit-tracker'
      fullPath: '/habit-tracker'
      preLoaderRoute: typeof AuthenticatedHabitTrackerRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/api/mobile/scans': {
      id: '/api/mobile/scans'
      path: '/api/mobile/scans'
      fullPath: '/api/mobile/scans'
      preLoaderRoute: typeof ApiMobileScansRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/mobile/risk-analysis': {
      id: '/api/mobile/risk-analysis'
      path: '/api/mobile/risk-analysis'
      fullPath: '/api/mobile/risk-analysis'
      preLoaderRoute: typeof ApiMobileRiskAnalysisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/mobile/recommendations': {
      id: '/api/mobile/recommendations'
      path: '/api/mobile/recommendations'
      fullPath: '/api/mobile/recommendations'
      preLoaderRoute: typeof ApiMobileRecommendationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/mobile/profile': {
      id: '/api/mobile/profile'
      path: '/api/mobile/profile'
      fullPath: '/api/mobile/profile'
      preLoaderRoute: typeof ApiMobileProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/mobile/habits': {
      id: '/api/mobile/habits'
      path: '/api/mobile/habits'
      fullPath: '/api/mobile/habits'
      preLoaderRoute: typeof ApiMobileHabitsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/mobile/habit-insights': {
      id: '/api/mobile/habit-insights'
      path: '/api/mobile/habit-insights'
      fullPath: '/api/mobile/habit-insights'
      preLoaderRoute: typeof ApiMobileHabitInsightsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/mobile/articles': {
      id: '/api/mobile/articles'
      path: '/api/mobile/articles'
      fullPath: '/api/mobile/articles'
      preLoaderRoute: typeof ApiMobileArticlesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/mobile/analyze': {
      id: '/api/mobile/analyze'
      path: '/api/mobile/analyze'
      fullPath: '/api/mobile/analyze'
      preLoaderRoute: typeof ApiMobileAnalyzeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/mobile/recommendations/generate': {
      id: '/api/mobile/recommendations/generate'
      path: '/generate'
      fullPath: '/api/mobile/recommendations/generate'
      preLoaderRoute: typeof ApiMobileRecommendationsGenerateRouteImport
      parentRoute: typeof ApiMobileRecommendationsRoute
    }
    '/api/mobile/auth/signup': {
      id: '/api/mobile/auth/signup'
      path: '/api/mobile/auth/signup'
      fullPath: '/api/mobile/auth/signup'
      preLoaderRoute: typeof ApiMobileAuthSignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/mobile/auth/login': {
      id: '/api/mobile/auth/login'
      path: '/api/mobile/auth/login'
      fullPath: '/api/mobile/auth/login'
      preLoaderRoute: typeof ApiMobileAuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedHabitTrackerRoute: typeof AuthenticatedHabitTrackerRoute
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRoute
  AuthenticatedRecommendationsRoute: typeof AuthenticatedRecommendationsRoute
  AuthenticatedRiskAnalysisRoute: typeof AuthenticatedRiskAnalysisRoute
  AuthenticatedScanRoute: typeof AuthenticatedScanRoute
  AuthenticatedShadesRoute: typeof AuthenticatedShadesRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedHabitTrackerRoute: AuthenticatedHabitTrackerRoute,
  AuthenticatedProfileRoute: AuthenticatedProfileRoute,
  AuthenticatedRecommendationsRoute: AuthenticatedRecommendationsRoute,
  AuthenticatedRiskAnalysisRoute: AuthenticatedRiskAnalysisRoute,
  AuthenticatedScanRoute: AuthenticatedScanRoute,
  AuthenticatedShadesRoute: AuthenticatedShadesRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

interface AdminRouteChildren {
  AdminApiDocsRoute: typeof AdminApiDocsRoute
  AdminArticlesRoute: typeof AdminArticlesRoute
  AdminRecommendationsRoute: typeof AdminRecommendationsRoute
  AdminScansRoute: typeof AdminScansRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminShadesRoute: typeof AdminShadesRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminApiDocsRoute: AdminApiDocsRoute,
  AdminArticlesRoute: AdminArticlesRoute,
  AdminRecommendationsRoute: AdminRecommendationsRoute,
  AdminScansRoute: AdminScansRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminShadesRoute: AdminShadesRoute,
  AdminUsersRoute: AdminUsersRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface ApiMobileRecommendationsRouteChildren {
  ApiMobileRecommendationsGenerateRoute: typeof ApiMobileRecommendationsGenerateRoute
}

const ApiMobileRecommendationsRouteChildren: ApiMobileRecommendationsRouteChildren =
  {
    ApiMobileRecommendationsGenerateRoute:
      ApiMobileRecommendationsGenerateRoute,
  }

const ApiMobileRecommendationsRouteWithChildren =
  ApiMobileRecommendationsRoute._addFileChildren(
    ApiMobileRecommendationsRouteChildren,
  )

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  AdminRoute: AdminRouteWithChildren,
  LoginRoute: LoginRoute,
  SignupRoute: SignupRoute,
  ApiMobileAnalyzeRoute: ApiMobileAnalyzeRoute,
  ApiMobileArticlesRoute: ApiMobileArticlesRoute,
  ApiMobileHabitInsightsRoute: ApiMobileHabitInsightsRoute,
  ApiMobileHabitsRoute: ApiMobileHabitsRoute,
  ApiMobileProfileRoute: ApiMobileProfileRoute,
  ApiMobileRecommendationsRoute: ApiMobileRecommendationsRouteWithChildren,
  ApiMobileRiskAnalysisRoute: ApiMobileRiskAnalysisRoute,
  ApiMobileScansRoute: ApiMobileScansRoute,
  ApiMobileAuthLoginRoute: ApiMobileAuthLoginRoute,
  ApiMobileAuthSignupRoute: ApiMobileAuthSignupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
